--START - EDA PROJECT N1--
--DIMENSION ANALYSIS--

-- Where do our customers come from? --/
SELECT DISTINCT country 
FROM gold.dim_customers;

--What are the main products (categories,subcategories)? --/
SELECT DISTINCT category, subcategory, product_name 
FROM gold.dim_products
ORDER BY 1,2,3;

--The first and last order date --/
SELECT MIN(order_date) FirstOrderDate,
		MAX(order_date) LastOrderDate,
		DATEDIFF(year, MIN(order_date), MAX(order_date)) OrderRangeY
FROM gold.fact_sales;

--Find the oldest, youngest, average customer age --/
SELECT DATEDIFF(year,MIN(birthdate), GETDATE()) Oldest_CustomerAge,
	   DATEDIFF(year,MAX(birthdate), GETDATE()) Youngest_CustomerAge,
	   AVG(DATEDIFF(year, birthdate, GETDATE())) AS Avg_CustomerAge
FROM gold.dim_customers;

--
--Business Key Metrics Report--

SELECT 'Total Sales' AS Measure_Name,
		SUM(sales_amount) as Measure_Value
		FROM gold.fact_sales
UNION ALL
SELECT 'Items Sold' AS Measure_Name, 
		SUM(quantity) AS Items_Quantity_Sold
		FROM gold.fact_sales
UNION ALL
SELECT 'Average Price' AS Measure_Name, 
		AVG(price) AS Avg_Price
		FROM gold.fact_sales
UNION ALL
SELECT 'Number of Orders' AS Measure_Name, 
		COUNT(DISTINCT Order_number) AS Num_Orders
		FROM gold.fact_sales
UNION ALL
SELECT 'Number of Products' AS Measure_Name, 
		COUNT(product_key) AS Num_Products
		FROM gold.dim_products
UNION ALL 
SELECT 'Number of Customers' AS measure_name, 
		COUNT(customer_key) AS Num_Customers
		FROM gold.dim_customers;

--MAGNITUDE ANALYSIS-- 

--Total number of customers by countries--
SELECT country, COUNT(customer_id) AS number_of_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY count(customer_id) DESC;

--Total customers by gender --
SELECT gender, COUNT(DISTINCT customer_id) AS customers 
FROM gold.dim_customers 
GROUP BY gender
ORDER BY customers DESC;

--Total products by category --
SELECT category, COUNT(product_id) Num_of_Products
FROM gold.dim_products
GROUP BY category
ORDER BY Num_of_Products DESC;

--Avg Cost for each category --
SELECT category, AVG(cost) as Avg_Cost
FROM gold.dim_products
GROUP BY category
ORDER BY Avg_Cost DESC;

--Total revenue generated by each category --
SELECT p.category,
		SUM(s.sales_amount) Total_Revenue
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_products AS p
ON p.product_key=s.product_key
GROUP BY p.category
ORDER BY Total_Revenue DESC;

--Total revenue generated by each customer --
SELECT c.customer_id, c.first_name, c.last_name, 
	SUM(s.sales_amount) AS Revenue_Per_Customer
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customers AS c
ON c.customer_key=s.customer_key
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY Revenue_Per_Customer DESC;

--Distribution of sold items across countries --
SELECT c.country, SUM(s.quantity) AS total_sold_items
FROM gold.dim_customers c
LEFT JOIN gold.fact_sales s
ON c.customer_key=s.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;

--RANKING ANALYSIS--

-- TOP 5 Products by Revenue Generated --
SELECT TOP 5 
p.product_name,
SUM(s.sales_amount) Total_Revenue
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_products AS p
ON p.product_key=s.product_key
GROUP BY product_name
ORDER BY Total_Revenue DESC;

--TOP 5 Products by Lowest Revenue Generated --
SELECT TOP 5 
p.product_name,
SUM(s.sales_amount) Total_Revenue
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_products AS p
ON p.product_key=s.product_key
GROUP BY product_name
ORDER BY Total_Revenue ASC;